### ISSUE TITLE
Error with URLs deployed on Heroku not responding

### ISSUE THREAD

**Issue by 41hulk** [neararabic/near-api-flutter#2]
# Affected Lines

https://github.com/neararabic/near-api-flutter/blob/f1eda8cc940e670b516a1d5dff14a550a3b65abd/example/lib/main.dart#L142
https://github.com/neararabic/near-api-flutter/blob/f1eda8cc940e670b516a1d5dff14a550a3b65abd/example/lib/main.dart#L144

# Problem
There's an error with both success and failure URLs i think the issue is Heroku not responding

# Author
Guy E. Ntare

**Comment by mhassanist** [comment]
Yea probably a problem there but these are meant to be replaced by your success and failure URLs anyway. Feel free to host any success/failure web pages and put your urls there.

**Comment by 41hulk** [comment]
Awesome! I thought it was some kind of NEAR success/failure URL. I'll build one
Thanks @mhassanist
